- src/zocalo/configuration/argparse.py
- src/zocalo/service/__init__.py
with `--live`/`--test` still being there for some deprecation period, but no longer advertised.
The default environment is still 'test', this will be addressed separately in the future
> zocalo.service: allow activating arbitrary environments

- HISTORY.rst
- src/zocalo/wrapper.py
and catch & ignore disconnection exceptions.
Status messages by themselves will not cause reconnection attempts.
> Keep status thread alive through disconnects

- HISTORY.rst
- contrib/site-configuration.yml
- docs/siteconfig.rst
- src/zocalo/__init__.py
- src/zocalo/cli/go.py
- src/zocalo/cli/wrap.py
- src/zocalo/configuration/__init__.py
- src/zocalo/configuration/argparse.py
- src/zocalo/service/__init__.py
- src/zocalo/wrapper.py
- tests/configuration/test_configuration.py
~~The default default is "live", which i think is sensible based on cli tools. Services default to test~~
Makes environment activation blocks consistent between go, wrap, and service instantiation. Default envs for cli tools and services can now be defined in the config under the `defaults` property.
> try to make env activation consistent and reusable

- src/zocalo/cli/go.py
- src/zocalo/cli/wrap.py
- src/zocalo/service/__init__.py
`zocalo.go`, `zocalo.wrap`, and `zocalo.service` (needs workflows v2.11) now all accept a `--transport` option, which can be predefined in the site configuration file.
> Make default transport configurable

- src/zocalo/configuration/__init__.py
- tests/configuration/test_configuration.py
This allows you to define e.g.:
foo: ~/bar.yml
which will correctly get expanded to:
foo: /path/to/home/bar.yml
instead of the current behaviour which is:
foo: /path/to/cwd/bar.yml
> Expand ~ in paths in configuration files

- HISTORY.rst
- README.rst
- setup.cfg
- src/zocalo/cli/queue_drain.py
- tests/cli/test_queue_drain.py
To drain one queue into another in a controlled manner
> New zocalo.queue_drain command

- HISTORY.rst
- src/zocalo/util/rabbitmq.py
- tests/util/test_rabbitmq.py
Utility function to return a `urllib.request.Request` object to query the RabbitMQ API using the credentials specified via `zocalo.configuration`.
> New zocalo.util.rabbitmq.http_api_request()

- src/zocalo/cli/wrap.py
- tests/cli/test_wrap.py
to emit a traceback on segmentation faults and other unexpected crashes.
> Enable faulthandler in zocalo.wrap

- .pre-commit-config.yaml
- HISTORY.rst
- requirements_dev.txt
- setup.cfg
- src/zocalo/cli/dlq_check.py
- src/zocalo/cli/dlq_reinject.py
- src/zocalo/util/rabbitmq.py
- tests/cli/test_dlq_check.py
- tests/util/test_rabbitmq.py
Provide a (not fully comprehensive) Python wrapper around the [RabbitMQ HTTP API](https://rawcdn.githack.com/rabbitmq/rabbitmq-server/v3.9.7/deps/rabbitmq_management/priv/www/api/index.html). Can be used to read various metrics useful for monitoring/health checks, and configuring exchanges, policies, queues, etc.
Adds explicit dependencies on [pydantic](https://pydantic-docs.helpmanual.io/) and [requests](https://docs.python-requests.org/) modules and a test dependency on [requests-mock](https://requests-mock.readthedocs.io/en/latest/).
Alternative to #136
> New zocalo.util.rabbitmq.RabbitMQAPI

- src/zocalo/util/rabbitmq.py
- tests/util/test_rabbitmq.py
Bindings are handled slightly differently to queues and exchanges in the RabbitMQ HTTP API. A `POST` is required rather than a `PUT` to the address `api/bindings/e/{exchange name}/{e, q}/{queue or exchange name}`. The `routing_key` and `arguments` can be declared in the body and a "name" (called the `properties_key`) is then created for the binding from the `routing_key` and a hash of `arguments`. A single binding can then be found at `api/bindings/e/{exchange name}/{e, q}/{queue or exchange name}/{properties_key}`. The proposed API allows for deletion of a single binding if `properties_key` is specified or of all bindings between a given source and destination otherwise.
Resolves #145
> Add support for bindings to `RabbitMQAPI`

- .azure-pipelines.yml
- HISTORY.rst
- setup.cfg
Will be required for #142. Conda-forge have dropped 3.6, and we never really used 3.7, so the impact of this might be rather low? Don't know about ESRF.
> Drop Python 3.6 and 3.7 support

- HISTORY.rst
- src/zocalo/cli/dlq_purge.py
- tests/cli/test_dlq_purge.py
Make changes necessary for `workflows>2.16` and add support for purging all queues on RabbitMQ.
> Fix `zocalo.dlq_purge` for RabbitMQ

- src/zocalo/util/rabbitmq.py
- tests/util/test_rabbitmq.py
When constructing a url to point to a binding queues and exchanges are denoted by `q` and `e` respectively. However, when binding information is returned in response to a `GET` request the `destination_type` is labelled as either `queue` or `exchange`. The result from the `GET` request then needs to be mapped to `q` or `e` for consistency and to correctly fill the `destination_type` field in `BindingInfo`.
> Fix for bindings API support

- src/zocalo/util/rabbitmq.py
- tests/util/test_rabbitmq.py
User tags are specified as a comma separated string but are returned by the management API as a list. 
As `UserInfo` inherits from `UserSpec` and `mypy` won't like a type change from `str` to `list` in a subclass I've made the type of tags in `UserSpec` `Union[str, List[str]]`. Unsure if that is the best solution.
> Fix `RabbitMQAPI.users()`

- HISTORY.rst
- src/zocalo/cli/dlq_reinject.py
- tests/cli/test_dlq_reinject.py
so that downstream services can take reinjection into account when
considering eg. timestamps and timeouts.
> Add 'dlq-reinjected' header to reinjected messages

- HISTORY.rst
- src/zocalo/cli/dlq_purge.py
- src/zocalo/cli/dlq_reinject.py
- tests/cli/test_dlq_purge.py
* ``zocalo.dlq_purge`` offers a ``--location`` flag to override where files are being written
* ``zocalo.dlq_reinject`` can again understand ``zocalo.dlq_purge`` output passed on stdin
* Tests now pass when running in an environment with `ZOCALO_CONFIG` and a DLQ dumping location set
* purge output was wrong, needed two leading spaces for filenames
* remove leftover print from purge command
* some pathlib/fstring updates
> zocalo.dlq_purge/reinject updates

- src/zocalo/cli/dlq_reinject.py
- tests/cli/test_dlq_reinject.py
The format of messages from `dlq_purge` has all headers placed under the header key with no secondary headers structure which is currently assumed by `dlq_reinject`.
`PikaTransport` squashes what RabbitMQ calls `headers` and other properties that Zocalo considers to be headers into a single `header` which is what is written out by `dlq_purge`. When reinjecting the message we drop the properties not in the original RabbitMQ `headers` from the header before reinjecting so this should be fine and `dlq_reinject` should not look for a secondary `headers` structure within the header.
> Fix header parsing in `dlq_reinject` for RabbitMQ

- HISTORY.rst
- src/zocalo/cli/configure_rabbitmq.py
The random salt used in password hashing is now seeded via a command line argument to make the hash reproducible so that a regularly run configurator doesn't detect a hashed password change and delete and recreate the users every time it runs.
> Add user removal to RabbitMQ configuration tool

- src/zocalo/cli/configure_rabbitmq.py
Nothing will happen if you do but best to avoid the API call anyway
> Don't try to delete the default exchanges when configuring rabbitmq

- src/zocalo/cli/configure_rabbitmq.py
- src/zocalo/util/rabbitmq.py
`zocalo.configure_rabbitmq` cli:
* Support for explicitly declaring exchanges
* Allow queues to bind to more than one exchange
> Support for delayed message exchanges

- src/zocalo/util/rabbitmq.py
- tests/cli/test_dlq_check.py
- tests/util/test_rabbitmq.py
This allows for failover for clustered nodes if one node is out of action.
Iteratively attempts to `GET` the `/health/checks/alarms` for each url contained in the comma-separated `base_url` field, returning an instance as soon as it can connect without a `ConnectionError`.
* Setup a session for all requests
* Add timeout parameters to get/post/put/delete.
A comma-separated `base_url` can be set via the `RabbitAPI` configuration plugin, e.g.:
```
plugin: rabbitmqapi
base_url: http://rabbitmq1.example.com:15672/api,http://rabbitmq2.example.com:15672/api,http://rabbitmq3.example.com:15672/api
username: admin
password: password
vhost: zocalo
```
A slightly more intrusive change would be to make the `RabbitAPI` configuration plugin to be more similar to the `Pika` configuration plugin, i.e.: …
> RabbitMQAPI: support comma-separated base_url

- HISTORY.rst
- docs/siteconfig.rst
- setup.cfg
- src/zocalo/cli/wrap.py
- src/zocalo/configuration/plugin_graylog.py
- src/zocalo/configuration/plugin_logging.py
- src/zocalo/service/__init__.py
- tests/configuration/test_plugin_logging.py
This plugin allows site-wide logging configuration.
That way `zocalo.wrap`, `zocalo.service`, `dlstbx.wrap`, `dlstbx.service`, etc. can all use the same setup
> Add a logging plugin

- src/zocalo/cli/configure_rabbitmq.py
- src/zocalo/util/rabbitmq.py
- tests/util/test_rabbitmq.py
This enables more advanced routing topologies using non-default exchanges and where the routing key != queue name
E.g.:
```
exchanges:
- name: breakfast
vhost: zocalo
type: topic
- names:
- ham.spam
- ham.eggs
- ham
settings:
queues:
type: quorum
bindings:
- source: breakfast
destination: ham.spam
- source: results
destination: ham.eggs
- source: breakfast
destination: ham
routing_key: ham.*
vhost: zocalo
```
Use `default_factory=dict` since input of `arguments=None` gets returns as `arguments={}` from the API this means that that repeated runs of the configure_rabbitmq cli don't repeatedly delete/create items
Remove `properties_key` from `BindingSpec` since you can't explicitly set this field
Correct `if_unused` and `if_empty` -> `if-unused` and `if-empty` in exchange/queue API calls
> Advanced binding configuration

- HISTORY.rst
- src/zocalo/cli/configure_rabbitmq.py
Making dlq explicit rather than implicit means that we can choose not to have a dlq for a specific queue.
To achieve the previous functionality (i.e. queue "foo" is given
a DLQ "dlq.foo" add e.g. the following:
```
- names:
- foo
- bar
settings:
queues:
type: quorum
dead-letter-routing-key-pattern: dlq.{name}
```
> Require explicit dead-letter-routing-key-pattern

- HISTORY.rst
- src/zocalo/cli/configure_rabbitmq.py
* This requires the user config file to be explicitly passed via the --user-config option rather than determined via the zocalo configuration. This makes it easier to use the same queue configuration file with different rabbitmq servers with (potentially) different users/passwords.
* Optionally disable implicit dlq creation: this enables using a queue that has already been explicitly defined elsewhere as a the dlq, allowing for more complex routing topologies.
> configure_rabbitmq: add --user-config option

- HISTORY.rst
- src/zocalo/cli/wrap.py
- src/zocalo/wrapper.py
Derived wrappers should now use `self.log.info()` etc rather than `logger.info()` to ensure the `recipe_ID` is included in the log message.
The inclusion of the `recipe_ID` in the log message was inadvertantly broken when using the new logging plugin #176
Fixes #192
Remove use of `ContextFilter` to add `recipe_ID` when using the graylog plugin as it is no longer needed since it is now already added using a LoggingAdapter.
> zocalo.wrapper: use LoggerAdapter to append recipe_ID to logs

- HISTORY.rst
- src/zocalo/cli/configure_rabbitmq.py
- src/zocalo/util/rabbitmq.py
- tests/util/test_rabbitmq.py
Without this, vhosts had to be configured manually ahead of running this script. With this PR, it should be possible to correctly configure a clean RabbitMQ server.
> Support for configuring rabbitmq vhosts

- HISTORY.rst
- src/zocalo/cli/configure_rabbitmq.py
I think this can be triggered by the creation of temporary queues (for example by the Zocalo system tests) between the api.queues() and api.bindings() calls.
> Downgrade no matching queue error to warning

- HISTORY.rst
- setup.cfg
- src/zocalo/service/dispatcher.py
- tests/service/test_dispatcher.py
Single point of contact service that takes in job meta-information (say, a data collection ID), a processing recipe, a list of recipes, or pointers to recipes stored elsewhere, and mangles these into something that can be processed by downstream services.
Subscribes to the processing_recipe queue.
The dispatcher service declares the following entry points:
`zocalo.services.dispatcher.filters`: functions that accept and return (and potentially modify) `message` and `parameters`
`zocalo.services.dispatcher.ready_for_processing`: functions that accept `message` and `parameters` and return a `bool` indicating whether or not a particular message is "ready for processing".
Taking heavy inspiration from #118
Closes #118
> Add Dispatcher service

- HISTORY.rst
- setup.cfg
- src/zocalo/cli/pickup.py
- tests/cli/test_pickup.py
This reads dropfiles from the `zocalo.go.fallback_location` directory which is where `zocalo.go` writes messages if the message broker is unavailable. When the message broker becomes available again, `zocalo.pickup` can be used to re-submit messages to the `processing_recipe` queue.
> New `zocalo.pickup` command

- HISTORY.rst
- setup.cfg
- src/zocalo/configuration/plugin_slurm.py
- src/zocalo/util/slurm/__init__.py
- src/zocalo/util/slurm/models.py
- tests/configuration/test_plugin_slurm.py
- tests/util/test_slurm.py
Add slurm zocalo config plugin.
Initial pydantic models generated from the API using [datamodel-code-generator](https://github.com/koxudaxi/datamodel-code-generator).
> Add minimal Slurm api for submitting jobs 

- HISTORY.rst
- src/zocalo/configuration/plugin_slurm.py
- src/zocalo/util/slurm/__init__.py
- tests/configuration/test_plugin_slurm.py
- tests/util/test_slurm.py
So that downstream applications can e.g. check expiry on the user token
> Expose various attributes on SlurmRestApi instances

- requirements_dev.txt
- requirements_doc.txt
- setup.cfg
sphinx-rtd-theme wasn't compatible with updated sphinx. We can update this separately.
Also, zocalo isn't compatible with pydantic 2 yet.
Freeze other dependencies listed in `requirements_dev.txt` - the whole purpose of having a requirements file is freezing the direct dependencies.
> Fix and freeze dependencies

- .bumpversion.cfg
- HISTORY.rst
- docs/conf.py
- pyproject.toml
- src/zocalo/__init__.py
Zocalo version v0.32.0 release
* Upgrade to Slurm REST API v0.0.40. [#248](https://github.com/DiamondLightSource/python-zocalo/pull/248)
* ``zocalo.configure_rabbitmq``: Show explicit error when VHost not created. [#241](https://github.com/DiamondLightSource/python-zocalo/pull/241)
> Bump version: 0.30.2 → 0.32.0

- HISTORY.rst
- src/zocalo/cli/dlq_purge.py
Now shows which queues messages came from, instead of mixing together outputs in somewhat arbitrary order. New output:
```
Looking for DLQ messages in 38 queues...
Found 13 DLQ messages in dlq.ispyb_connector
Message 1 (2025-06-16 13:27:41) exported:
/dls/tmp/zocalo/DLQ/2025-06-16/msg-20250616-132741-000-1
Message 2 (2025-06-16 13:27:41) exported:
/dls/tmp/zocalo/DLQ/2025-06-16/msg-20250616-132741-000-2
Message 3 (2025-06-16 13:27:41) exported:
/dls/tmp/zocalo/DLQ/2025-06-16/msg-20250616-132741-000-3
Message 4 (2025-06-16 13:27:41) exported:
/dls/tmp/zocalo/DLQ/2025-06-16/msg-20250616-132741-000-4
Done.
```
Also, accepts `dlq.*` names in rabbitmq, stripping off the `dlq.` part if present.
> dlq_purge: Show what queues messages came from
